version: '3'

services:
  database_project:
    image: mariadb:10.9-jammy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: dziennik
      MYSQL_USER: user
      MYSQL_PASSWORD: asdf
    ports:
      - '13306:3306'
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

