version: '3.2'

services:
  dbp-mariadb:
    restart: always
    container_name: dbp-mariadb-container
    image: mariadb:10.9-jammy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - '${HOST_PORT}:3306'
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ${PWD}/sql
        target: /sql

volumes:
  mariadb-data:
