version: '3'

services:
  dbp-mariadb:
    restart: always
    container_name: dbp-mariadb-container
    image: mariadb:10.9-jammy
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: gradebook
      MYSQL_USER: user
      MYSQL_PASSWORD: asdf
    ports:
      - '13306:3306'
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      - ${PWD}/sql:/sql

