version: '3.2'

services:
  dbp-mariadb:
    restart: always
    container_name: dbp-mariadb-container
    image: mariadb:10.9-jammy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - '${HOST_DB_PORT}:3306'
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ${PWD}/sql
        target: /sql
  dbp-app:
    restart: always
    container_name: dbp-app-container
    image: docker.io/bitnami/laravel:9
    ports:
      - '${HOST_APP_PORT}:8000'
    environment:
      - DB_HOST=dbp-mariadb
      - DB_PORT=3306
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
    volumes:
      - type: bind
        source: ${PWD}/app
        target: /app

volumes:
  mariadb-data:
